# Generated by Django 5.1.1 on 2024-09-18 17:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=cloudinary.models.CloudinaryField(default='cat pic', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
